rule crime_win32_exe_rat_netwire{ 
       meta:
              description = "AlienSpy"
              author = "Fidelis Cybersecurity"
              reference = "Fidelis Threat Advisory #1017 - Phishing in Plain Sight - June 9, 2015"
              hash = "fd5a753347416484ab01712786c407c4" 

       strings:
              $sa1 = "StubPath"
              $sa2 = "CONNECT"
              $sa3 = "200 OK"
              $sa4 = "GET"
              $sa5 = "Host"
              $sa6 = "Connection"
              $sa7 = "Firefox"
              $sa8 = "Chrome"
              $sa9 = "Opera"
              $sa10 = "Outlook"
              $sa11 = "NSS_Shutdown"
              $sa12 = "NSSBase64_DecodeBuffer"
              $sa13 = "NSS_Init"
              $sa14 = "NSS_Shutdown"
              $sa15 = "name" nocase
              $sa16 = "password"
              $sa17 = "Server"
              $sa18 = "LANMANNT"
              $sa19 = "SERVERNT"
              $sa20 = "[Backspace]"
              $sa21 = "[Enter]"
              $sa22 = "[Tab]"
              $sa23 = "[Print Screen]"
              $sa24 = "mozsqlite"
              $sa25 = "nssutil"
              $sa26 = "sqlite"
              $sa27 = "Email"
              $sa28 = "POP3 User"
              $sa29 = "POP3 Server"
              $sa30 = "POP3 Password"
              $sa31 = "IMAP User"
              $sa32 = "IMAP Server"
              $sa33 = "IMAP Password"
              $sa34 = "HTTP User"
              $sa35 = "HTTP Server"
              $sa36 = "HTTP Password"
              $sa37 = "SMTP User"
              $sa38 = "SMTP Server"
              $sa39 = "SMTP Password"

       condition:
              (uint16(0) == 0x5A4D) and (all of them)
}