/*
Generated by Yara-Rules
On 27-03-2019
*/
include "EMAIL_Cryptowall.yar"
include "attachment.yar"
include "bank_rule.yar"
include "email_Ukraine_BE_powerattack.yar"
include "image.yar"
include "scam.yar"
include "urls.yar"