/*
Generated by Yara-Rules
On 27-03-2019
*/
include "Maldoc_APT10_MenuPass.yar"
include "Maldoc_APT19_CVE-2017-1099.yar"
include "Maldoc_APT_OLE_JSRat.yar"
include "Maldoc_CVE-2017-0199.yar"
include "Maldoc_CVE_2017_11882.yar"
include "Maldoc_CVE_2017_8759.yar"
include "Maldoc_Contains_VBE_File.yar"
include "Maldoc_DDE.yar"
include "Maldoc_Dridex.yar"
include "Maldoc_Hidden_PE_file.yar"
include "Maldoc_MIME_ActiveMime_b64.yar"
include "Maldoc_PDF.yar"
include "Maldoc_PowerPointMouse.yar"
include "Maldoc_Suspicious_OLE_target.yar"
include "Maldoc_UserForm.yar"
include "Maldoc_VBA_macro_code.yar"
include "Maldoc_Word_2007_XML_Flat_OPC.yar"
include "Maldoc_malrtf_ole2link.yar"
include "maldoc_somerules.yar"