/*
Generated by Yara-Rules
On 27-03-2019
*/
include "WShell_APT_Laudanum.yar"
include "WShell_ASPXSpy.yar"
include "WShell_PHP_Anuna.yar"
include "WShell_PHP_in_images.yar"
include "WShell_THOR_Webshells.yar"
include "Wshell_ChineseSpam.yar"
include "Wshell_fire2013.yar"